#!/bin/bash
# Gather the staged files - to make sure changes are saved only for these files.
stagedFiles=$(git diff --staged --name-only)

# run spotless apply
./gradlew spotlessApply

status=$?

if [ "$status" = 0 ] ; then
    # Add staged file changes to git
    for file in $stagedFiles; do
      if test -f "$file"; then
        git add $file
      fi
    done
    #Exit
    exit 0
else
    echo 1>&2 "Spotless Apply found violations it could not fix."
    #Exit
    exit 1
fi